"""empty message

Revision ID: 11361be8c9f5
Revises: ea0066e69ec5
Create Date: 2023-11-25 02:16:47.409812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11361be8c9f5'
down_revision = 'ea0066e69ec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('planet_fav_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('char_fav_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('favorites_char_fav_key', type_='unique')
        batch_op.drop_constraint('favorites_planet_fav_key', type_='unique')
        batch_op.create_foreign_key(None, 'planets', ['planet_fav_id'], ['id'])
        batch_op.create_foreign_key(None, 'people', ['char_fav_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('planet_fav')
        batch_op.drop_column('char_fav')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('char_fav', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('planet_fav', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('favorites_planet_fav_key', ['planet_fav'])
        batch_op.create_unique_constraint('favorites_char_fav_key', ['char_fav'])
        batch_op.drop_column('char_fav_id')
        batch_op.drop_column('planet_fav_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
